### ISSUE TITLE
question about controlling qolsys panel

### ISSUE THREAD

**Issue by ifuchs** [mzac/qolsys_client#2]
Will this code permit me to get realtime status and to control devices from home assistant? My security company is replacing an HAI system (which is integrated with HA) with a qolsys 4. I need a way for HA to get status and to control devices that will be moved to the qolsys. Is this possible?

**Comment by mzac** [comment]
Please use this integration for Home Assistant, it is much more up to date compared to my original implemention.

https://github.com/roopesh/ad-qolsys

You can also follow the discussion on the Home Assistant community here:

https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405
